#!/usr/bin/env bash
# =============================================================================
# build.sh - assemble src/*.sh modules into the single-file lsshm.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$ROOT_DIR/src"
OUT_FILE="$ROOT_DIR/lsshm.sh"
VERSION_FILE="$ROOT_DIR/VERSION"

# Module concatenation order. common.sh MUST come first, main.sh last.
MODULES=(
    common.sh
    platform.sh
    privileges.sh
    backup.sh
    server.sh
    server_config.sh
    rollback.sh
    users.sh
    authorized_keys.sh
    local_keys.sh
    ssh_agent.sh
    hosts.sh
    known_hosts.sh
    logs.sh
    audit.sh
    updater.sh
    cli.sh
    dialog.sh
    main.sh
)

VERSION="$(tr -d '[:space:]' <"$VERSION_FILE")"
BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    cat <<EOF
#!/usr/bin/env bash
# =============================================================================
# LSSHM - Local SSH Manager
# Version: $VERSION
# Built:   $BUILD_DATE
#
# This file is generated by scripts/build.sh from the modules in src/.
# Do not edit it by hand; edit the modules and rebuild.
#
# A simple local OpenSSH server, client, user access and key management tool
# for Linux (Windows support is planned through lsshm.ps1).
# =============================================================================

set -euo pipefail

EOF

    for module in "${MODULES[@]}"; do
        printf '\n# ===== src/%s ' "$module"
        printf '%.0s=' $(seq 1 $((60 - ${#module})))
        printf '\n'
        # Strip a leading shebang from any module (there should be none).
        sed '1{/^#!/d;}' "$SRC_DIR/$module"
    done

    cat <<'EOF'

# ===== entry point ===========================================================
lsshm_main "$@"
EOF
} >"$tmp"

# Inject the real version in place of the build token.
sed "s/@@LSSHM_VERSION@@/$VERSION/g" "$tmp" >"$OUT_FILE"
chmod +x "$OUT_FILE"

# Syntax check the assembled file.
if ! bash -n "$OUT_FILE"; then
    echo "build.sh: syntax check failed for $OUT_FILE" >&2
    exit 1
fi

# Regenerate SHA256SUMS for the distributable artifacts.
# Normalize to text mode ("hash  file") so installers never choke on "hash *file".
(
    cd "$ROOT_DIR"
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum lsshm.sh VERSION | sed 's/ \*/  /' >SHA256SUMS
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 lsshm.sh VERSION >SHA256SUMS
    fi
)

echo "Built $OUT_FILE (version $VERSION)"
echo "Updated SHA256SUMS"
